yaml
theme:jekyll-theme-minimal
title:Awuduchatha DigitalStorefront
description:High-quality assets for our product catalog

# This tell GitHub which colour to use for links and highlights
#(we will add the background coluor in the next step)

